/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cashFlow.GUI;

import Tables.AccountTable;
import cashFlow.Listeners.ValuesChangeAction;
import cashFlow.Listeners.ValuesChangeEvent;
import db.Control.ModelControl;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author f98877a
 */
public class AddAccountScreen extends javax.swing.JFrame implements ValuesChangeAction {

    private ValuesChangeEvent vc;

    /**
     * Creates new form AddAccountScreen
     */
    public AddAccountScreen() {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        accNameTfd = new javax.swing.JTextField();
        accValueTfd = new javax.swing.JTextField();
        accTypeTfd = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        addAccSaveBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        accNameTfd.setText("Ex. Itau");
        accNameTfd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accNameTfdActionPerformed(evt);
            }
        });

        accValueTfd.setText("0");
        accValueTfd.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        accValueTfd.setSelectionEnd(10);

        accTypeTfd.setText("Ex. CC, Poupança");
        accTypeTfd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accTypeTfdActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome da conta");

        jLabel2.setText("Saldo inicial");

        jLabel3.setText("Tipo da conta");

        addAccSaveBtn.setText("Salvar");
        addAccSaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAccSaveBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(accNameTfd)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 66, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(accTypeTfd, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(accValueTfd, javax.swing.GroupLayout.Alignment.TRAILING)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addAccSaveBtn)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accNameTfd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accValueTfd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accTypeTfd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addAccSaveBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void accTypeTfdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accTypeTfdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accTypeTfdActionPerformed

    private void addAccSaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAccSaveBtnActionPerformed
        // TODO add your handling code here:

        AccountTable accountTable = new AccountTable();

        accountTable.setName(accNameTfd.getText());
        accountTable.setValue(Integer.parseInt(accValueTfd.getText()));
        accountTable.setType(accTypeTfd.getText());

        if (Integer.parseInt(accValueTfd.getText()) >= 0) {
            accountTable.setStatus("Positive");
        } else {
            accountTable.setStatus("Negative");
        }

        accountTable.setTotalExpense(0);
        accountTable.setTotalIncome(0);

        try {
            ModelControl.save(accountTable);

        } catch (SQLException ex) {
            Logger.getLogger(AddAccountScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
        vc.setValuesChanged();
    }//GEN-LAST:event_addAccSaveBtnActionPerformed

    private void accNameTfdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accNameTfdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accNameTfdActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accNameTfd;
    private javax.swing.JTextField accTypeTfd;
    private javax.swing.JTextField accValueTfd;
    private javax.swing.JButton addAccSaveBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setPanelToChange(ValuesChangeEvent panel) {
        this.vc = panel;
    }

}
