/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cashFlow.GUI;

import Tables.AccountTable;
import Tables.CashFlowInfo;
import cashFlow.Listeners.ValuesChangeAction;
import cashFlow.Listeners.ValuesChangeEvent;
import db.Control.ModelControl;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.NumberFormatter;

/**
 *
 * @author f98877a
 */
public class AddAccountScreen extends javax.swing.JFrame implements ValuesChangeAction {

    private ValuesChangeEvent vc;

    /**
     * Creates new form AddAccountScreen
     */
    public AddAccountScreen() {
        initComponents();

        configScreenItens();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        accNameTfd = new javax.swing.JTextField();
        accTypeTfd = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        addAccSaveBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        accValueTfd = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        accNameTfd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accNameTfdActionPerformed(evt);
            }
        });

        accTypeTfd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accTypeTfdActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome da conta");

        jLabel2.setText("Saldo inicial");

        jLabel3.setText("Tipo da conta");

        addAccSaveBtn.setText("Salvar");
        addAccSaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAccSaveBtnActionPerformed(evt);
            }
        });

        jLabel4.setText("R$");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addAccSaveBtn)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(accNameTfd)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(accValueTfd, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                                .addContainerGap())))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(accTypeTfd, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accNameTfd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(accValueTfd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accTypeTfd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addAccSaveBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void accTypeTfdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accTypeTfdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accTypeTfdActionPerformed

    private void addAccSaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAccSaveBtnActionPerformed
        // TODO add your handling code here:

        AccountTable accountTable = new AccountTable();
        accountTable.setName(accNameTfd.getText());
        //Value
        String value = accValueTfd.getText();
        value = value.replace(".", "");
        value = value.replace(",", ".");
        Double num = new Double(value);
        accountTable.setValue(num);

        accountTable.setType(accTypeTfd.getText());

        if (accountTable.getValue() >= 0) {
            accountTable.setStatus(CashFlowInfo.POSITIVE);
        } else {
            accountTable.setStatus(CashFlowInfo.NEGATIVE);
        }

        accountTable.setDay(LocalDate.now().getDayOfMonth());
        accountTable.setMonth(LocalDate.now().getMonthValue());
        accountTable.setYear(LocalDate.now().getYear());

        try {
            ModelControl.save(accountTable);

        } catch (SQLException ex) {
            Logger.getLogger(AddAccountScreen.class.getName()).log(Level.SEVERE, null, ex);
        }

        vc.setValuesChanged(this, null);
        this.dispose();
    }//GEN-LAST:event_addAccSaveBtnActionPerformed

    private void accNameTfdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accNameTfdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accNameTfdActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accNameTfd;
    private javax.swing.JTextField accTypeTfd;
    private javax.swing.JFormattedTextField accValueTfd;
    private javax.swing.JButton addAccSaveBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setPanelToChange(ValuesChangeEvent panel) {
        this.vc = panel;
    }

    private void configScreenItens() {

        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);

        //Value in currency
        DecimalFormat dFormat = new DecimalFormat("#,###,###.00");
        NumberFormatter pAmount = new NumberFormatter(dFormat);
        pAmount.setAllowsInvalid(false);
        accValueTfd.setFormatterFactory(new DefaultFormatterFactory(pAmount));
    }

}
