/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cashFlow.GUI;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author F98877A
 */
public class StatementsScreen extends javax.swing.JFrame {

    TableView tableView = new TableView();

    /**
     * Creates new form statementsScreen
     */
    public StatementsScreen() {
        initComponents();

        try {
            tableView.fillExpensesTable(6);
        } catch (Exception ex) {
            Logger.getLogger(StatementsScreen.class.getName()).log(Level.SEVERE, null, ex);
        }

        mountLayout();
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        stsPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        jLabel1.setText("Movimentações");

        javax.swing.GroupLayout stsPanelLayout = new javax.swing.GroupLayout(stsPanel);
        stsPanel.setLayout(stsPanelLayout);
        stsPanelLayout.setHorizontalGroup(
            stsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        stsPanelLayout.setVerticalGroup(
            stsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 292, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(stsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(242, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(stsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel stsPanel;
    // End of variables declaration//GEN-END:variables

    private void mountLayout() {
        javax.swing.GroupLayout layout = null;
        javax.swing.GroupLayout.ParallelGroup pg = null;
        javax.swing.GroupLayout.SequentialGroup sg = null;

        layout = new javax.swing.GroupLayout(stsPanel);

        stsPanel.setLayout(layout);

        pg = layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING);

        pg.addComponent(tableView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE);

        layout.setVerticalGroup(pg);

        sg = layout.createSequentialGroup();

        sg.addComponent(tableView, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE);
        sg.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED);

        pg = layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING);

        pg.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sg);

        layout.setHorizontalGroup(pg);
    }
}
