/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cashFlow.GUI;

import Tables.AccountTable;
import Tables.ExpenseTable;
import Tables.IncomeTable;
import cashFlow.GUI.Renderers.ModifiedListRenderer;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.time.LocalDate;
import java.time.Month;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author F98877A
 */
public class StatementsScreen extends javax.swing.JFrame {

    TableView tableView = new TableView();
    private Month currentMonth;
    private Object dataType = null;
    private AccountTable account;

    public Object getDataType() {
        return dataType;
    }

    public void setDataType(Object dataType) {
        this.dataType = dataType;
    }

    public AccountTable getAccount() {
        return account;
    }

    public void setAccount(AccountTable account) {
        this.account = account;
    }

    /**
     * Creates new form statementsScreen
     */
    public StatementsScreen() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        stsPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        stsMonthCBx = new javax.swing.JComboBox();
        stsTypeLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        jLabel1.setText("Movimentações");

        javax.swing.GroupLayout stsPanelLayout = new javax.swing.GroupLayout(stsPanel);
        stsPanel.setLayout(stsPanelLayout);
        stsPanelLayout.setHorizontalGroup(
            stsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        stsPanelLayout.setVerticalGroup(
            stsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 336, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Lucida Console", 1, 11)); // NOI18N
        jLabel2.setText("Mês:");

        stsTypeLbl.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(stsTypeLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 211, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(stsMonthCBx, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(stsMonthCBx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stsTypeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(stsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox stsMonthCBx;
    private javax.swing.JPanel stsPanel;
    private javax.swing.JLabel stsTypeLbl;
    // End of variables declaration//GEN-END:variables

    private void mountLayout() {
        javax.swing.GroupLayout layout = null;
        javax.swing.GroupLayout.ParallelGroup pg = null;
        javax.swing.GroupLayout.SequentialGroup sg = null;

        layout = new javax.swing.GroupLayout(stsPanel);

        stsPanel.setLayout(layout);

        pg = layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING);

        pg.addComponent(tableView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE);

        layout.setVerticalGroup(pg);

        sg = layout.createSequentialGroup();

        sg.addComponent(tableView, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE);
        sg.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED);

        pg = layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING);

        pg.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sg);

        layout.setHorizontalGroup(pg);
    }

    public void configScreen() {

        stsMonthCBx.removeAllItems();
        for (Object e : Month.values()) {
            stsMonthCBx.addItem((Month) e);
        }
        stsMonthCBx.setRenderer(new ModifiedListRenderer());
        stsMonthCBx.setSelectedItem(LocalDate.now().getMonth());
        currentMonth = (Month) stsMonthCBx.getSelectedItem();

        stsMonthCBx.addActionListener((ActionEvent e) -> {
            currentMonth = (Month) stsMonthCBx.getSelectedItem();
            fillTable();
        });

        fillTable();

        mountLayout();
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    private void fillTable() {

        if (dataType != null) {
            if (dataType instanceof ExpenseTable) {
                stsTypeLbl.setText("Despesas");
                stsTypeLbl.setForeground(Color.red);
                try {
                    tableView.fillExpensesTable(currentMonth, account.getOid());
                } catch (Exception ex) {
                    Logger.getLogger(StatementsScreen.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else if (dataType instanceof IncomeTable) {
                stsTypeLbl.setText("Receitas");
                stsTypeLbl.setForeground(Color.GREEN);
                try {
                    tableView.fillIncomeTable(currentMonth, account.getOid());
                } catch (Exception ex) {
                    Logger.getLogger(StatementsScreen.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }
}
