/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cashFlow.GUI;

import Tables.AccountTable;
import Tables.CashFlowInfo;
import Tables.CategoryTable;
import Tables.ExpenseTable;
import Tables.IncomeTable;
import db.Control.ModelControl;
import db.tableInterfaces.TableModel;
import java.time.LocalDate;
import java.time.Month;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import utils.TableUtils;

/**
 *
 * @author F98877A
 */
public class TableView extends javax.swing.JPanel {

    protected List tableHeader;

    /**
     * Creates new form TableView
     */
    public TableView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        stsPanel = new javax.swing.JPanel();
        stsScroll = new javax.swing.JScrollPane();
        stsTable = new javax.swing.JTable();

        stsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        stsScroll.setViewportView(stsTable);

        javax.swing.GroupLayout stsPanelLayout = new javax.swing.GroupLayout(stsPanel);
        stsPanel.setLayout(stsPanelLayout);
        stsPanelLayout.setHorizontalGroup(
            stsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(stsScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        stsPanelLayout.setVerticalGroup(
            stsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(stsScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(stsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(stsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel stsPanel;
    private javax.swing.JScrollPane stsScroll;
    private javax.swing.JTable stsTable;
    // End of variables declaration//GEN-END:variables

    public void fillExpensesTable(Month month, int acc) throws Exception {

        List expenses = null;
        List ord = new ArrayList();
        ExpenseTable expenseTable = null;
        CategoryTable categ = null;
        AccountTable accountTable = null;

        tableHeader = new ArrayList();

        for (String ExpColumn : CashFlowInfo.ExpColumns) {
            tableHeader.add(ExpColumn);
            ord.add(ExpColumn);
        }

        try {
            stsTable = TableUtils.create(tableHeader, ord, new ArrayList());
        } catch (Exception ex) {
            Logger.getLogger(TableView.class.getName()).log(Level.SEVERE, null, ex);
        }
        stsScroll.setViewportView(stsTable);

        expenses = ModelControl.selectWithParam(ExpenseTable.class, month.ordinal() + 1, acc);       // month.ordinal() returns from 0 to 11, so add 1

        for (int it = 0; it < expenses.size(); it++) {

            if (expenses.get(it) instanceof ExpenseTable) {
                expenseTable = (ExpenseTable) expenses.get(it);

                TableModel categoryLoad = ModelControl.load(CategoryTable.class, expenseTable.getCategory());

                if (categoryLoad instanceof CategoryTable) {
                    categ = (CategoryTable) categoryLoad;
                }

                TableModel accountLoad = ModelControl.load(AccountTable.class, expenseTable.getAccOid());

                if (accountLoad instanceof AccountTable) {
                    accountTable = (AccountTable) accountLoad;
                }

                TableUtils.addRow(stsTable);

                LocalDate date = LocalDate.of(expenseTable.getYear(), month, expenseTable.getDay());

                TableUtils.setCellValue(date.toString(), stsTable, it, tableHeader.get(0));

                TableUtils.setCellValue(expenseTable.getDescription(), stsTable, it, tableHeader.get(1));
                TableUtils.setCellValue(expenseTable.getValue(), stsTable, it, tableHeader.get(2));
                TableUtils.setCellValue(categ.getCategory(), stsTable, it, tableHeader.get(3));
                TableUtils.setCellValue(accountTable.getName(), stsTable, it, tableHeader.get(4));

                stsTable.getColumnModel().getColumn(1).setPreferredWidth(200);
                stsTable.getColumnModel().getColumn(4).setPreferredWidth(100);
                stsTable.setEnabled(false);
            }
        }

        stsTable.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
        stsTable.getTableHeader().setReorderingAllowed(false);

    }

    public void fillIncomeTable(Month month, int acc) throws Exception {

        List incomes;
        List ord = new ArrayList();
        IncomeTable incomeTable;
        CategoryTable categ = null;
        AccountTable accountTable = null;

        tableHeader = new ArrayList();

        for (String ExpColumn : CashFlowInfo.ExpColumns) {
            tableHeader.add(ExpColumn);
            ord.add(ExpColumn);
        }

        try {
            stsTable = TableUtils.create(tableHeader, ord, new ArrayList());
        } catch (Exception ex) {
            Logger.getLogger(TableView.class.getName()).log(Level.SEVERE, null, ex);
        }
        stsScroll.setViewportView(stsTable);

        incomes = ModelControl.selectWithParam(IncomeTable.class, month.ordinal() + 1, acc);       // month.ordinal() returns from 0 to 11, so add 1

        for (int it = 0; it < incomes.size(); it++) {

            if (incomes.get(it) instanceof IncomeTable) {
                incomeTable = (IncomeTable) incomes.get(it);

                TableModel categoryLoad = ModelControl.load(CategoryTable.class, incomeTable.getCategory());

                if (categoryLoad instanceof CategoryTable) {
                    categ = (CategoryTable) categoryLoad;
                }

                TableModel accountLoad = ModelControl.load(AccountTable.class, incomeTable.getAccOid());

                if (accountLoad instanceof AccountTable) {
                    accountTable = (AccountTable) accountLoad;
                }

                TableUtils.addRow(stsTable);

                LocalDate date = LocalDate.of(incomeTable.getYear(), month, incomeTable.getDay());

                TableUtils.setCellValue(date.toString(), stsTable, it, tableHeader.get(0));

                TableUtils.setCellValue(incomeTable.getDescription(), stsTable, it, tableHeader.get(1));
                TableUtils.setCellValue(incomeTable.getValue(), stsTable, it, tableHeader.get(2));
                TableUtils.setCellValue(categ.getCategory(), stsTable, it, tableHeader.get(3));
                TableUtils.setCellValue(accountTable.getName(), stsTable, it, tableHeader.get(4));

                stsTable.getColumnModel().getColumn(1).setPreferredWidth(200);
                stsTable.getColumnModel().getColumn(4).setPreferredWidth(100);
                stsTable.setEnabled(false);
            }
        }

        stsTable.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
        stsTable.getTableHeader().setReorderingAllowed(false);

    }

}
